//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempoIDE.ProgramData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TempoIDE.ProgramData.ProgramFiles", typeof(ProgramFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///    &lt;menu Name=&quot;File&quot;&gt;
        ///        &lt;command Name=&quot;New solution&quot;/&gt;
        ///        &lt;command Name=&quot;Open solution...&quot;/&gt;
        ///        &lt;command Name=&quot;Close solution&quot;/&gt;
        ///        &lt;divider/&gt;
        ///        &lt;command Name=&quot;Settings&quot;/&gt;
        ///    &lt;/menu&gt;
        ///    
        ///    &lt;menu Name=&quot;Edit&quot;&gt;
        ///        &lt;command Name=&quot;Copy&quot;&gt;
        ///            &lt;Keybind&gt;
        ///                &lt;Key&gt;LeftCtrl&lt;/Key&gt;
        ///                &lt;Key&gt;C&lt;/Key&gt;
        ///            &lt;/Keybind&gt;
        ///        &lt;/command&gt;
        ///        
        ///        &lt;command Name=&quot;Paste&quot;&gt;
        ///            &lt;Keybind&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app_commands {
            get {
                return ResourceManager.GetString("app_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///    &lt;keywords&gt;
        ///        &lt;kw&gt;abstract&lt;/kw&gt;
        ///        &lt;kw&gt;as&lt;/kw&gt;
        ///        &lt;kw&gt;base&lt;/kw&gt;
        ///        &lt;kw&gt;bool&lt;/kw&gt;
        ///        &lt;kw&gt;break&lt;/kw&gt;
        ///        &lt;kw&gt;by&lt;/kw&gt;
        ///
        ///        &lt;kw&gt;byte&lt;/kw&gt;
        ///        &lt;kw&gt;case&lt;/kw&gt;
        ///        &lt;kw&gt;catch&lt;/kw&gt;
        ///        &lt;kw&gt;char&lt;/kw&gt;
        ///        &lt;kw&gt;checked&lt;/kw&gt;
        ///        &lt;kw&gt;class&lt;/kw&gt;
        ///
        ///        &lt;kw&gt;const&lt;/kw&gt;
        ///        &lt;kw&gt;continue&lt;/kw&gt;
        ///        &lt;kw&gt;decimal&lt;/kw&gt;
        ///        &lt;kw&gt;default&lt;/kw&gt;
        ///        &lt;kw&gt;delegate&lt;/kw&gt;
        ///        &lt;kw&gt;do&lt;/kw&gt;
        ///        
        ///        &lt;kw&gt;double&lt;/kw&gt;
        ///        &lt;kw&gt;desc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string intellisense_cs {
            get {
                return ResourceManager.GetString("intellisense_cs", resourceCulture);
            }
        }
    }
}
